apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedserviceaccountrequests.rhoas.redhat.com
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedServiceAccountRequest
    plural: managedserviceaccountrequests
    shortNames:
    - msar
    singular: managedserviceaccountrequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        additionalProperties:
          type: object
        status:
          properties:
            message:
              type: string
            updated:
              type: string
            serviceAccountSecretName:
              type: string
            additionalProperties:
              type: object
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
