kind: Secret
apiVersion: v1
metadata:
  name: rh-managed-services-api-accesstoken
  namespace: rhoas-operator
stringData:
  value: >-
    eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2MTQ4MDYyMDgsImp0aSI6IjFjYjA1Y2MwLTFiODctNDhiYi04ZDRhLTFmNjdiNDM2Zjc4NSIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpzdXBpdHRtYUByZWRoYXQuY29tIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImNsb3VkLXNlcnZpY2VzIiwibm9uY2UiOiJjZjQzOWY2YS1mMTc0LTRhYTEtYWE4ZS1lYzY5ZDY0NWYwYjAiLCJzZXNzaW9uX3N0YXRlIjoiY2M5NmFlMzEtNTkwMS00YmI3LThiMGEtNzRiNGE5MTNjYmUyIiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MifQ.6K-LsrJHs5TrWFqFg6knpFN9qrcmCaGeXcCctinEBZY
type: Opaque
