apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: rhoas-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - 'customresourcedefinitions'  
  verbs:
    - get
    - list
    - watch  
- apiGroups:
  - rhoas.redhat.com
  resources:
  - 'managedkafkaconnections'
  - 'managedkafkaconnections/status'
  - 'managedkafkaconnections/finalizers'
  - 'managedkafkarequests'
  - 'managedkafkarequests/status'
  - 'managedkafkarequests/finalizers'
  - 'managedserviceaccountrequests'
  - 'managedserviceaccountrequests/status'
  - 'managedserviceaccountrequests/finalizers'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch