apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: rhoas-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - 'customresourcedefinitions'  
  verbs:
    - get
    - list
    - watch  
- apiGroups:
  - rhoas.redhat.com
  resources:
  - 'kafkaconnections'
  - 'kafkaconnections/status'
  - 'kafkaconnections/finalizers'
  - 'cloudservicesrequests'
  - 'cloudservicesrequests/status'
  - 'cloudservicesrequests/finalizers'
  - 'cloudserviceaccountrequests'
  - 'cloudserviceaccountrequests/status'
  - 'cloudserviceaccountrequests/finalizers'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch