/*
 * Managed Service API
 * Managed Service API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KafkaRequestPayload
 */
public class KafkaRequestPayloadTest {
    private final KafkaRequestPayload model = new KafkaRequestPayload();

    /**
     * Model tests for KafkaRequestPayload
     */
    @Test
    public void testKafkaRequestPayload() {
        // TODO: test KafkaRequestPayload
    }

    /**
     * Test the property 'cloudProvider'
     */
    @Test
    public void cloudProviderTest() {
        // TODO: test cloudProvider
    }

    /**
     * Test the property 'multiAz'
     */
    @Test
    public void multiAzTest() {
        // TODO: test multiAz
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

}
