
apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: rhosak-openshift-getting-started-quickstart
spec:
  displayName: Getting Started with Red Hat OpenShift Streams for Apache Kafka
  icon: >-
    data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFk
    b2JlIElsbHVzdHJhdG9yIDI1LjIuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246
    IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5z
    PSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMu
    b3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAzNyAzNyIgc3R5
    bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMzcgMzc7IiB4bWw6c3BhY2U9InByZXNlcnZl
    Ij4KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCS5zdDB7ZmlsbDojRUUwMDAwO30KCS5zdDF7Zmls
    bDojRkZGRkZGO30KPC9zdHlsZT4KPGc+Cgk8cGF0aCBkPSJNMjcuNSwwLjVoLTE4Yy00Ljk3LDAt
    OSw0LjAzLTksOXYxOGMwLDQuOTcsNC4wMyw5LDksOWgxOGM0Ljk3LDAsOS00LjAzLDktOXYtMThD
    MzYuNSw0LjUzLDMyLjQ3LDAuNSwyNy41LDAuNUwyNy41LDAuNXoiCgkJLz4KCTxwYXRoIGNsYXNz
    PSJzdDAiIGQ9Ik0xNi41LDE4LjEyYy0xLjcyLDAtMy4xMi0xLjQtMy4xMi0zLjEyczEuNC0zLjEy
    LDMuMTItMy4xMnMzLjEyLDEuNCwzLjEyLDMuMTJTMTguMjIsMTguMTIsMTYuNSwxOC4xMnoKCQkg
    TTE2LjUsMTMuMTJjLTEuMDMsMC0xLjg4LDAuODQtMS44OCwxLjg4czAuODQsMS44OCwxLjg4LDEu
    ODhzMS44OC0wLjg0LDEuODgtMS44OFMxNy41MywxMy4xMiwxNi41LDEzLjEyeiIvPgoJPHBhdGgg
    Y2xhc3M9InN0MSIgZD0iTTEyLjk0LDExLjA2bC0yLTJjLTAuMDgtMC4wOC0wLjE4LTAuMTMtMC4y
    OS0wLjE1Yy0wLjAzLTAuMDEtMC4wNS0wLjAxLTAuMDctMC4wMQoJCWMtMC4xMS0wLjAxLTAuMjIt
    MC4wMS0wLjMyLDAuMDNjMCwwLDAsMCwwLDBjLTAuMDcsMC4wMy0wLjEzLDAuMDctMC4xOCwwLjEy
    Yy0wLjAxLDAuMDEtMC4wMSwwLjAxLTAuMDIsMC4wMWwtMiwyCgkJYy0wLjI0LDAuMjQtMC4yNCww
    LjY0LDAsMC44OGMwLjEyLDAuMTIsMC4yOCwwLjE4LDAuNDQsMC4xOHMwLjMyLTAuMDYsMC40NC0w
    LjE4bDAuOTMtMC45M1YyMi41YzAsMC4zNSwwLjI4LDAuNjIsMC42MiwwLjYyCgkJczAuNjItMC4y
    OCwwLjYyLTAuNjJWMTEuMDFsMC45MywwLjkzYzAuMjQsMC4yNCwwLjY0LDAuMjQsMC44OCwwQzEz
    LjE5LDExLjcsMTMuMTksMTEuMywxMi45NCwxMS4wNnoiLz4KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9
    Ik0yMi41LDE4LjEyYy0wLjM0LDAtMC42Mi0wLjI4LTAuNjItMC42MnYtNWMwLTAuMzUsMC4yOC0w
    LjYyLDAuNjItMC42MnMwLjYyLDAuMjgsMC42MiwwLjYydjUKCQlDMjMuMTIsMTcuODUsMjIuODQs
    MTguMTIsMjIuNSwxOC4xMnoiLz4KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0yMC41LDI1LjEyYy0x
    LjcyLDAtMy4xMi0xLjQtMy4xMi0zLjEyczEuNC0zLjEyLDMuMTItMy4xMnMzLjEyLDEuNCwzLjEy
    LDMuMTJTMjIuMjIsMjUuMTIsMjAuNSwyNS4xMnoKCQkgTTIwLjUsMjAuMTJjLTEuMDMsMC0xLjg4
    LDAuODQtMS44OCwxLjg4czAuODQsMS44OCwxLjg4LDEuODhzMS44OC0wLjg0LDEuODgtMS44OFMy
    MS41MywyMC4xMiwyMC41LDIwLjEyeiIvPgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTI4Ljk0LDI1
    LjA2Yy0wLjI0LTAuMjQtMC42NC0wLjI0LTAuODgsMGwtMC45MywwLjkzVjEyLjVjMC0wLjM1LTAu
    MjgtMC42Mi0wLjYyLTAuNjJzLTAuNjIsMC4yOC0wLjYyLDAuNjIKCQl2MTMuNDlsLTAuOTMtMC45
    M2MtMC4yNC0wLjI0LTAuNjQtMC4yNC0wLjg4LDBjLTAuMjQsMC4yNC0wLjI0LDAuNjQsMCwwLjg4
    bDIsMmMwLjA2LDAuMDYsMC4xMywwLjExLDAuMjEsMC4xNAoJCWMwLjA4LDAuMDMsMC4xNiwwLjA1
    LDAuMjQsMC4wNWMwLjA4LDAsMC4xNi0wLjAyLDAuMjQtMC4wNWMwLDAsMCwwLDAsMGMwLjA3LTAu
    MDMsMC4xMy0wLjA3LDAuMTgtMC4xMgoJCWMwLjAxLTAuMDEsMC4wMS0wLjAxLDAuMDItMC4wMWwy
    LTJDMjkuMTksMjUuNywyOS4xOSwyNS4zLDI4Ljk0LDI1LjA2eiIvPgoJPHBhdGggY2xhc3M9InN0
    MCIgZD0iTTE0LjUsMjUuMTJjLTAuMzQsMC0wLjYyLTAuMjgtMC42Mi0wLjYydi01YzAtMC4zNSww
    LjI4LTAuNjIsMC42Mi0wLjYyczAuNjIsMC4yOCwwLjYyLDAuNjJ2NQoJCUMxNS4xMiwyNC44NSwx
    NC44NCwyNS4xMiwxNC41LDI1LjEyeiIvPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTI2LjUsMTgu
    MTJjLTAuMzQsMC0wLjYyLTAuMjgtMC42Mi0wLjYydi01YzAtMC4zNSwwLjI4LTAuNjIsMC42Mi0w
    LjYyczAuNjIsMC4yOCwwLjYyLDAuNjJ2NQoJCUMyNy4xMiwxNy44NSwyNi44NCwxOC4xMiwyNi41
    LDE4LjEyeiIvPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTEwLjUsMjUuMTJjLTAuMzQsMC0wLjYy
    LTAuMjgtMC42Mi0wLjYydi01YzAtMC4zNSwwLjI4LTAuNjIsMC42Mi0wLjYyczAuNjIsMC4yOCww
    LjYyLDAuNjJ2NQoJCUMxMS4xMiwyNC44NSwxMC44NCwyNS4xMiwxMC41LDI1LjEyeiIvPgo8L2c+
    Cjwvc3ZnPgo=
  tags:
    - streams
    - kafka
  durationMinutes: 10
  description: Learn how to set up your first Apache Kafka instance in Red Hat OpenShift Streams for Apache Kafka.
  prerequisites:
    - A Red Hat identity
    - You're logged in to the Application Services web console at https://console.redhat.com/beta/application-services.
  introduction: >-
    Welcome to the Red Hat OpenShift Streams for Apache Kafka Getting Started quick start.
    In this quick start, you'll learn how to create and inspect a Kafka instance, create a service account to connect an application or service to the instance, and create a topic in the instance.
  tasks:
    - title: Inspecting a Kafka instance in Streams for Apache Kafka
      description: >-
        Use the [Streams for Apache Kafka web console](https://console.redhat.com/beta/application-services/streams) to create and configure a Kafka instance for your applications or services.


        To access Streams for Apache Kafka, you need to be logged in with a Red Hat identity. If you do not have a Red Hat identity, you can create one by following the link on the login screen.


        A Kafka instance in Streams for Apache Kafka includes a Kafka cluster, bootstrap server, and the configurations needed to connect to producer and consumer services.

        1. In the [web console of Application Services](https://console.redhat.com/beta/application-services), select **Kafka Instances** in the **Streams for Apache kafka** menu. Click *Create Kafka instance*.

        1. Enter a unique **Name**, such as `my-first-kafka-instance`, and select the relevant **Cloud region** option. All other fields are preconfigured.

        1. Click *Create instance* to start the creation process for your Kafka instance.


        The new Kafka instance is listed in the instances table. In some cases, you might need to wait several minutes for the instance creation process to complete.

        When the instance **Status** is **Ready**, you can start using the Kafka instance. You can use the options icon (three vertical dots) to view instance details, connect to the instance, change the instance owner, or delete the instance.


        NOTE: Although you can see Kafka instances created by other users in your organization, you might not be able manage or connect to those instances. Only the instance owner or users with permissions to access the instance can edit or delete the instance, access the associated service account and topics, or connect to the instance.

      review:
        instructions: |-
          Is the new Kafka instance listed in the instances table?

          Is the state of the new Kafka instance shown as **Ready**?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: >-
          You have completed this task!
        failed: Try the steps again.
    - title: Creating a service account to connect to a Kafka instance in Streams for Apache Kafka
      description: >-
        To connect your applications or services to a Kafka instance in the Streams for Apache Kafka web console,
        you need to create a service account, copy and save the generated credentials, and copy and save the bootstrap server endpoint.
        You’ll use the service account information later when you configure your application.

        1. In the **Kafka Instances** page of the web console, for the relevant Kafka instance that you want to connect to,
        select the options icon (three vertical dots) and click **Connection**.

        1. In the **Connection** page, copy the **Bootstrap server** endpoint to a secure location.
        This is the bootstrap server endpoint that you'll need for connecting to this Kafka instance.

        1. Click **Create service account** to generate the credentials that you'll use to connect to this Kafka instance.
        Provide a name, for example `my-service-account`. You can leave the description field empty. Click **Create**.

        1. Copy the generated **Client ID** and **Client Secret** to a secure location.

            IMPORTANT: The generated credentials are displayed only one time,
            so ensure that you have successfully and securely saved the copied credentials before closing the credentials window.

        1. After you save the generated credentials to a secure location, select the confirmation check box in the credentials window and close the window.

            You'll use the boostrap server and service account information that you saved to configure your application to connect to your Kafka instances when you're ready.
            For example, if you plan to use [Kafkacat](https://github.com/edenhill/kafkacat) to interact with your Kafka instance,
            you'll use this information to set your bootstrap server and client environment variables.
      review:
        instructions: |-
          Did you save the bootstrap server endpoint to a secure location?

          Did you save the client credentials to a secure location?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: >-
          You have completed this task!
        failed: Try the steps again.
    - title: Setting permissions for a service account in a Kafka instance in Streams for Apache Kafka
      description: >-
        After you create a service account to connect to a Kafka instance, you must also set the appropriate level of access for that new account in the Access Control List (ACL) of the Kafka instance. Streams for Apache Kafka uses ACLs provided by Kafka that enable you to manage how other user accounts and service accounts are permitted to interact with the Kafka resources that you create.

        1. In the **Kafka Instances** page of the web console, click the name of the Kafka instance that you want the service account to access.

        1. Click the **Access** tab to view the current ACL for this instance.

        1. Click **Manage access**, use the **Account** drop-down menu to select the service account that you previously created, and click **Next**.

        1. Under **Assign Permissions**, use the drop-down menus to set the permissions shown in the following list for this service account. Click **Add** to add each new resource permission.

            These permissions enable applications associated with the service account to create and delete topics in the instance, to produce and consume messages in any topic in the instance, and to use any consumer group and any producer.

            **Example ACL permissions for a new service account**
            - **Topic**: ```Is``` = ```*```, ```Allow```, ```All```
            - **Consumer group**: ```Is``` = ```*```, ```Allow```, ```Read```
            - **Transactional ID**: ```Is``` = ```*```, ```Allow```, ```All```

        1. After you add these permissions for the service account, click **Save** to finish.
      review:
        instructions: |-
          Are the new permissions for the service account listed in the **Access** page of the Kafka instance?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: >-
          You have completed this task!
        failed: Try the steps again.
    - title: Creating a Kafka topic in Streams for Apache Kafka
      description: >-
        When you have a Kafka instance available, you can create Kafka topics to start producing and consuming messages in your services.

        1. In the **Kafka Instances** page of the web console, click on the name of the Kafka instance that you want to add a topic to.

        1. Select the **Topics** tab, click **Create topic**, and follow the guided steps to define the topic details.
        Click **Next** to complete each step and click **Finish** to complete the setup.

            **Topic name**: Enter a unique topic name, such as ```my-first-kafka-topic```.

            **Partitions**: Set the number of partitions for this topic. This example sets the partition to ```1``` for a single partition.
            Partitions are distinct lists of messages within a topic and enable parts of a topic to be distributed over multiple brokers in the cluster.
            A topic can contain one or more partitions, enabling producer and consumer loads to be scaled.

            NOTE: You can increase the number of partitions later, but you cannot decrease them.

            **Message retention**: Set the message retention time to the relevant value and increment.
            This example sets the retention to ```1 day```.
            Keep the **Retention size** set to ```Unlimited``` (the default).
            Message retention time is the amount of time that messages are retained in a topic before they are deleted or compacted, depending on the cleanup policy.


            **Replicas**: Set the number of partition replicas for the topic and the minimum number of follower replicas that must be in sync with a partition leader.
            In the current version of Streams for Apache Kafka the values are fixed and set to ```3``` for the number of replicas and ```2``` for the in-sync replicas.
            Replicas are copies of partitions in a topic.
            Partition replicas are distributed over multiple brokers in the cluster to ensure topic availability if a broker fails.
            When a follower replica is in sync with a partition leader, the follower replica can become the new partition leader if needed.

        After you complete the topic setup, the new Kafka topic is listed in the topics table.
        You can now start producing and consuming messages to and from this topic using services that you connect to this instance.
      review:
        instructions: |-
          Is the new Kafka topic listed in the topics table?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: >-
          You have completed this task!
        failed: Try the steps again.
    - title: Viewing metrics for a Kafka instance in Streams for Apache Kafka
      description: >-
        After you create Kafka topics in your Kafka instance, you can start producing and consuming messages using methods such as [Kafka](https://kafka.apache.org/downloads) scripts, [Kafkacat](https://github.com/edenhill/kcat), or a [Quarkus](https://quarkus.io/) application.

        After you produce and consume messages in your services, you can return to the Kafka instance in the web console and use the **Dashboard** page to view metrics for the instance and topics. The metrics help you understand the performance and data usage for your Kafka instance and topics.

        - In the **Kafka Instances** page of the web console, click the name of the Kafka instance and select the **Dashboard** tab.

            When you create your Kafka instance and topics, the **Dashboard** page is initially empty. After you start producing and consuming messages in your services, you can return to this page to view related metrics.

            NOTE: In some cases, after you start producing and consuming messages, you might need to wait several minutes for the latest metrics to appear. You might also need to wait until your instance and topics contain enough data for metrics to appear.

            After your topics contain data, the following metrics are available:

            - **Kafka instance metrics**
                - **Used disk space**: Used disk space is the amount of disk space used by the Kafka brokers in the instance. This metric enables you to assess available disk space relative to the limit. To reduce used disk space, you can adjust topic retention time or other topic properties as needed.

            - **Topic metrics**
                - **Total bytes**: Total bytes is the total incoming and outgoing bytes for all topics or for a selected topic in the Kafka instance. This metric enables you to assess data transfer in and out of your Kafka instance. To modify incoming and outgoing bytes, you can adjust topic message size or other topic properties as needed.
      review:
        instructions: |-
          Did you note how to navigate to the instance **Dashboard** page to view metrics later?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: >-
          You have completed this task!
        failed: Try the steps again.
  conclusion: >-
    Congratulations! You successfully completed the Red Hat OpenShift Streams for Apache Kafka Getting Started quick start,
    and are now ready to use the service.
  nextQuickStart:
    - rhosak-openshift-kafkacat-toolscontainer-quickstart
