apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedserviceaccountrequests.rhoas.redhat.com
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedServiceAccountRequest
    plural: managedserviceaccountrequests
    shortNames:
    - msar
    singular: managedserviceaccountrequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceAccountName:
              type: string
            serviceAccountDescription:
              type: string
            serviceAccountSecretName:
              type: string
            accessTokenSecretName:
              type: string
          type: object
        status:
          properties:
            message:
              type: string
            updated:
              type: string
            serviceAccountSecretName:
              type: string
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  status:
                    type: string
                  lastTransitionTime:
                    type: string
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
  preserveUnknownFields: false
