apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceregistryconnections.rhoas.redhat.com
  annotations:
    service.binding/registryUrl: 'path={.status.registryUrl}'
    ## Additional binding metadata required for Quarkus
    service.binding/converter: 'path={.status.metadata.converter}'
    service.binding/registryGlobalId: 'path={.status.metadata.registryGlobalId}'
    ## Lowercase versions for old versions of quarkus (to be removed later)
    service.binding/registryurl: 'path={.status.registryUrl}'
    service.binding/registryglobalid: 'path={.status.metadata.registryGlobalId}'
spec:
  group: rhoas.redhat.com
  names:
    kind: ServiceRegistryConnection
    plural: serviceregistryconnections
    shortNames:
    - src
    singular: serviceregistryconnection
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              accessTokenSecretName:
                type: string
              serviceRegistryId:
                type: integer
              credentials:
                properties:
                  serviceAccountSecretName:
                    type: string
                type: object
            type: object
            ## temporary required to workaround lack of scheduling issue with the operator SDK
            x-kubernetes-preserve-unknown-fields: true
          status:
            properties:
              message:
                nullable: true
                type: string
              metadata:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              updated:
                nullable: true
                type: string
              registryUrl:
                nullable: true
                type: string
              serviceAccountSecretName:
                nullable: true
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    lastTransitionGeneration:
                      type: integer          
                      format: int64
                      nullable: true                                   
            type: object
        type: object
