apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedservicesrequests.rhoas.redhat.com
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedServicesRequest
    plural: managedservicesrequests
    shortNames:
      - mscr
    singular: managedservicesrequest
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                accessTokenSecretName:
                  type: string
              type: object
            status:
              properties:
                message:
                  type: string
                  nullable: true
                updated:
                  type: string
                  nullable: true
                lastUpdate:
                  type: string
                  nullable: true
                conditions:
                  type: array
                  nullable: true
                  items:
                    type: object
                    properties:
                        type:
                          type: string
                        reason:
                          type: string
                        message:
                          type: string
                        status:
                          type: string
                        lastTransitionTime:
                          type: string
                userKafkas:
                  type: array
                  nullable: true
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      created:
                        type: string
                      provider:
                        type: string
                      region:
                        type: string
                      owner:
                        type: string
                      bootstrapServerHost:
                        type: string
                      updatedAt:
                        type: string
                      createdAt:
                        type: string
                      status:
                        type: string
              type: object
          type: object
  preserveUnknownFields: false
