---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-operator
rules:
  - apiGroups:
      - rhoas.redhat.com
    resources:
      - "*"
      - "*/finalizers"
    verbs: [get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
    verbs: [get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
      - rhoas.redhat.com
    resources:
      - managedkafkaconnection
      - managedkafkaconnections
      - managedkafkarequest
      - managedkafkarequests
      - managedserviceaccountrequest
      - managedserviceaccountrequests
    verbs: [get, list, create, update, delete, deletecollection, watch]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoas-operator
subjects:
- kind: ServiceAccount
  name: rhoas-operator
roleRef:
  kind: Role
  name: rhoas-operator
  apiGroup: rbac.authorization.k8s.io
---