=== Prerequisites

 - Java 11+
 - mvn
 - OpenShift Client (or kubernetes)

= Building and Devloping

The operator is written in Java as a multi module Maven project. The easiest way to build and run the operator locally is 

[source, bash]
----
 mvn install
 cd source/rhoas
 mvn quarkus:dev
----

This will compile the operator and run it in development mode using link:quarkus.io[Quarkus]. Please note, it will connect to whichever OpenShift cluster you are logged into with `oc login`.

== Updating Custom Resource Definitions

To update CRDs, you will need to edit the files in the 
link:https://github.com/bf2fc6cc711aee1a0c2a/operator/tree/main/olm/olm-template[OLM-template directory]. It is very important that the files in link:https://github.com/bf2fc6cc711aee1a0c2a/operator/tree/main/olm[the parent directory] are not disturbed as they are part of the OLM catalog history and are used by the out GitHub actions to create new OLM bundles and deploy them correctly.

== Operator Container Build

The Operator container is built by link:https://quarkus.io/guides/container-image[Quarkus JIB]. The configuration is provided by link:https://github.com/bf2fc6cc711aee1a0c2a/operator/blob/main/source/rhoas/src/main/resources/application.properties[application.properties]. The link:https://github.com/bf2fc6cc711aee1a0c2a/operator/blob/main/.github/workflows/release.yml#L32[GitHub action release workflow] contains an example of these values being overidden to release the operator. 