
=== Installing the Operator CatalogSource

==== Prerequisites

- OpenShift (kubernetes cluster)
- OperatorHub/OLM installed

==== Into OpenShift Marketplace (openshift-marketplace)

> NOTE: This installation method requires elevated cluster privileges since it writes to the *openshift-marketplace* namespace. 

The RHOAS Operator can be added as a CatalogSource in the *openshift-marketplace* using this CR:

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoas-operators
  namespace: openshift-marketplace
spec:
  displayName: RHOAS Operators
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/rhoas/service-operator-registry:autolatest
  priority: -400
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 260s
EOD
----

==== Into an Alternative Namespace

In this example we add the RHOAS Operator CatalogSource to the *rhoas-operator* namespace.

Create a CatalogSource:

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoas-operators
  namespace: rhoas-operator
spec:
  displayName: rhoas
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/rhoas/service-operator-registry:autolatest
  priority: -400
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 260s
EOD
----

=== Creating an Operator Subscription and OperatorGroup

==== Using OpenShift OperatorHub

Wait for the CatalogSource to load and synchronise with OpenShift OperatorHub. This process takes about five minutes.

Next, use a *dedicated-admin* or *cluster-admin* account and open your OpenShift cluster's OperatorHub. Type "rhoas" into the _filter_ field, and select the RHOAS Operator.

Follow the on screen wizard to install the operator into the namespace(s) of your choosing. Once the operator is installed, you may begin using it.

==== Installation on custom namespace using CR

Create a RHOAS Operator Subscription using this CR:

> Note: This CR *sourceNamespace* is set to "rhoas-operator". Change this to your own namespace. For example "openshift-marketplace" if you installed the CatalogSource there.

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhoas-operator.openshift-operators: ""
  name: rhoas-operator
spec:
  channel: beta
  installPlanApproval: Manual
  name: rhoas-operator
  source: rhoas-operators
  sourceNamespace: rhoas-operator
  startingCSV: rhoas-operator.0.2.1
EOD
----

Create an OperatorGroup to make the Operator available to other namespaces:

> Note: A global OperatorGroup example is provided below. You can restrict the target namespaces using a link:{https://docs.openshift.com/container-platform/4.7/operators/understanding/olm/olm-understanding-operatorgroups.html}[*selector* or *targetNamespaces*].

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhoas-group
  namespace: rhoas-operator
EOD
----

==== Configuring The Operator

You may configure the Operator by setting `config` values on the Subscription object which are passed to the pod. For example, the following Subscription resource will create a pod with memory limits : 

----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhoas-operator.openshift-operators: ""
  name: rhoas-operator
spec:
  channel: beta
  installPlanApproval: Automatic
  name: rhoas-operator
  source: rhoas-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhoas-operator.0.6.5
  config:
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
----

The operator also has several values which may be set via environment variables. These can be passed to the pod via the Subscription object as well.

 * AUTH_SERVERURL : The SSO service which exchanges tokens, defaults to `https://sso.redhat.com/auth/realms/redhat-external`
 * AUTH_CLIENTID :  The SSO client client-id, defaults to `cloud-services`
 * AUTH_TOKENPATH : The path to use with AUTH_SERVERURL to exchange the access token, defaults to `protocol/openid-connect/token`
 * CLOUD_SERVICES_API : The base path for the cloud services API, defaults to `https://api.stage.openshift.com`
