apiVersion: rhoas.redhat.com/v1alpha1
kind: ManagedKafkaConnection
metadata:
  name: test453-serviceapi
  namespace: rhoas-operator-testing
spec:
  accessTokenSecretName: rh-managed-services-api-accesstoken
  kafkaId: "1oLRVYm5q1Zx43mA0eIhsumYQ27"
  credentials:
    serviceAccountSecretName: service-account-credentials
# status:
#   message: "created"
#   updated: 2020-12-10T17:02:30Z
#   boostrapServer:
#     host: kafka--ltosqyk-wsmt-t-elukpkft-bg.apps.ms-bv8dm6nbd3jo.cx74.s1.devshift.org:443'
#   serviceAccountSecretName: service-account-123-credentials
