== Installation of Operator

> NOTE: Operator is currently in Beta state and not available on in OperatorHub

=== Installing the Operator

==== Prerequisites

- OpenShift (kubernetes cluster)
- OperatorHub/OLM installed

==== OpenShift Marketplace (openshift-marketplace)

> NOTE: This installation method requires elevated cluster privileges. 

The RHOAS Operator can be added as a CatalogSource in the *openshift-marketplace* using this CR.

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoas-operators
  namespace: openshift-marketplace
spec:
  displayName: RHOAS Operators
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/rhoas/service-operator-registry:autolatest
  priority: -400
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 260s
EOD
----

The CatalogSource will be loaded and sync'd with your OpenShift OperatorHub. This process takes about five minutes.

As *dedicated-admin* or *cluster-admin*, open your OpenShift cluster's OperatorHub. Type "rhoas" into the _filter_ field, and select the RHOAS Operator.

Follow the on screen wizard to install the operator. Once the operator is installed, you may begin using it.

==== Specific Namespace

In this example we add the RHOAS Operator CatalogSource to the *rhoas-operator* namespace.

Create a CatalogSource:

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoas-operators
  namespace: rhoas-operator
spec:
  displayName: rhoas
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/rhoas/service-operator-registry:autolatest
  priority: -400
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 260s
EOD
----

Create the RHOAS Operator Subscription:

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhoas-operator.openshift-operators: ""
  name: rhoas-operator
spec:
  channel: beta
  installPlanApproval: Manual
  name: rhoas-operator
  source: rhoas-operators
  sourceNamespace: rhoas-operator
  startingCSV: rhoas-operator.0.2.1
EOD
----

Create an OperatorGroup to make the Operator available to other namespaces:

> Note: A global OperatorGroup example is provided below. You can restrict the target namespaces using a link:{https://docs.openshift.com/container-platform/4.2/operators/understanding_olm/olm-understanding-operatorgroups.html#olm-operatorgroups-target-namespace_olm-understanding-operatorgroups}[*selector* or *targetNamespaces*].

----
kubectl apply -f - << EOD
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhoas-group
  namespace: rhoas-operator
EOD
----

