# This workflow bumps the version of the secondsun images and publish thems.
# If this looks wrong it is because it is temporary, we should not be using my 
# quay repo. -- Summers 20210203
name: Secondsun Bump, Build, Push

on:
  push:
    branches:  
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version
      run: 'olm/autoupdate.sh ${{ secrets.quay_robotaccount }} ${{ secrets.quay_robottoken }}'

    - name: Load version number
      id: version-number
      run: echo "::set-output name=version::$(cat olm/version)"
    - name: Commit updated version
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}            
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and run Unit tests
      run: mvn install --file pom.xml --no-transfer-progress -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=${{ steps.version-number.outputs.version }} -Dquarkus.container-image.push=true -Dquarkus.container-image.username=${{ secrets.quay_robotaccount}} -Dquarkus.container-image.password=${{ secrets.quay_robottoken}}
    - name: Login to Quay.io
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.quay_robotaccount }}
        password: ${{ secrets.quay_robottoken }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: olm
        file: ./olm/index.Dockerfile
        platforms: linux/amd64
        push: true
        tags: quay.io/secondsun/rhoas-registry:autolatest
        build-args: |
            QUAY_USER=${{ secrets.quay_robotaccount }}
            QUAY_PASSWORD=${{ secrets.quay_robottoken }}
            VERSION=${{ steps.version-number.outputs.version }}
            
      

